apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-hypervisor-exporter.fullname" . }}
  labels:
    {{- include "prometheus-hypervisor-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-hypervisor-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 15s
      path: {{ .Values.metrics.path }}
      relabelings:
        - targetLabel: job
          replacement: node-exporter