apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "setup.fullname" . }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    {{- include "setup.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.setup.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "setup.labels" . | nindent 8 }}
        {{- with .Values.setup.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.setup.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.setup.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command:
            {{- include "idurar-erp-crm.mongodb.await" . | nindent 12 }}
          {{- with .Values.setup.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.setup.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DATABASE
              value: {{ include "idurar-erp-crm.mongodb.url" . | quote }}
            {{- range $name, $value := .Values.setup.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
      {{- with .Values.setup.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.setup.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.setup.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.setup.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}